---
Resources:
  WebServer1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-09d95fab7fff3776c
      InstanceType: t2.micro
      KeyName: aws_linux_server
      SecurityGroups:
        - default
        - SG-WEB-SERVER
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash -xe
            sudo yum update -y
            sudo yum install httpd -y
            sudo service httpd start
            sudo chkconfig httpd on
            sudo usermod -a -G apache ec2-user
            sudo chown -R ec2-user:apache /var/www/html
            cd /var/www/html
            echo "<html><h1>Hello World</h1></html>" > index.html 
  WebServer2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-09d95fab7fff3776c
      InstanceType: t2.micro
      KeyName: aws_linux_server
      SecurityGroups:
        - default
        - SG-WEB-SERVER
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash -xe
            sudo yum update -y
            sudo yum install httpd -y
            sudo service httpd start
            sudo chkconfig httpd on
            sudo usermod -a -G apache ec2-user
            sudo chown -R ec2-user:apache /var/www/html
            cd /var/www/html
            echo "<html><h1>Hello World</h1></html>" > index.html 